// Pages

import { lazy } from "react";

export const StoreHome = lazy(() => import('./home/StoreHome'))
export const StoreSales = lazy(() => import('./sales/StoreSales'))
export const StoreSalesAdd = lazy(() => import('./salesAdd/StoreSalesAdd'))
export const StoreReception = lazy(() => import('./reception/StoreReception'))
export const StoreReceptionAdd = lazy(() => import('./receptionAdd/StoreReceptionAdd'))
export const StoreCashier = lazy(() => import('./cashier/StoreCashier'))
export const StorePreparationAdd = lazy(() => import('./preparationAdd/StorePreparationAdd'))
export const StoreProvider = lazy(() => import('./provider/StoreProvider'))
export const StoreProviderAdd = lazy(() => import('./providerAdd/StoreProviderAdd'))
export const StoreCustomer = lazy(() => import('./customer/StoreCustomer'))
export const StoreCustomerAdd = lazy(() => import('./customerAdd/StoreCustomerAdd'))
export const StoreCustomerEdit = lazy(() => import('./customerEdit/StoreCustomerEdit'))
export const StoreExpense = lazy(() => import('./expense/StoreExpense'))
export const StoreExpenseAdd = lazy(() => import('./expenseAdd/StoreExpenseAdd'))
export const StoreDebt = lazy(() => import('./debt/StoreDebt'))
export const StoreDebtAdd = lazy(() => import('./debtAdd/StoreDebtAdd'))
export const StoreReportProvider = lazy(() => import('./reportProvider/StoreReportProvider'))
export const StoreReportProviderAdd = lazy(() => import('./reportProviderAdd/StoreReportProviderAdd'))
export const StoreReportCashier = lazy(() => import('./reportCashier/StoreReportCashier'))
export const StoreReportAllCustomer = lazy(() => import('./reportAllCustomer/StoreReportAllCustomer'))
export const StoreTransferToFreezer = lazy(() => import('./transferToFreezer/StoreTransferToFreezer'))
export const StoreTransferToFreezerAdd = lazy(() => import('./transferToFreezerAdd/StoreTransferToFreezerAdd'))
export const StoreReportMassa = lazy(() => import('./reportMassa/StoreReportMassa'))
export const StoreReportProviderAllNew = lazy(() => import('./reportProviderAllNew/StoreReportProviderAllNew'))
export const StoreReportProviderNew = lazy(() => import('./reportProviderNew/StoreReportProviderNew'))
export const StoreSalary = lazy(() => import('./salary/StoreSalary'))
export const StoreSalaryAdd = lazy(() => import('./salaryAdd/StoreSalaryAdd'))